### ISSUE TITLE
Please explain the 'run composer' step in the readme

### ISSUE THREAD

**Issue by companje** [3DHubs/sdk-php#1]
The current readme.md just says: "run composer."

I think it means that I should download composer from 'https://getcomposer.org/doc/00-intro.md' and follow the steps there?

I'm running OSX and try the following:

```
  curl -sS https://getcomposer.org/installer | php
  php composer.phar install
```
Is this the correct way of doing things?

**Comment by bram-rongen** [comment]
Hi Rick,

'Run composer' is indeed a little bit cryptic. We will add some more guidance for people unfamiliar with composer.

Thanks!
