### ISSUE TITLE
Improper request URL

### ISSUE THREAD

**Issue by slavicd** [3DHubs/sdk-php#3]
The request gets sent to https://www.3dhubs.com/api/v1//api/v1/model. Clearly untested code.

**Comment by bram-rongen** [comment]
Hey Slavicd, can you supply us with the code to replicate this?

**Comment by slavicd** [comment]
Try any service methods like creating a cart or uploading a model. the above example was for $hubs3d->createModel();

**Comment by bram-rongen** [comment]
Fixed in: https://github.com/3DHubs/sdk-php/commit/33c231d51fea624b9200fc69dc2664545c39724c
